In [1]:
import pandas as pd
data = pd.read_csv("data/test.csv")
data.head()

,id,origin_host,origin_port,response_host,response_port,flow_duration,forward_packets_per_sec,backward_packets_per_sec,flow_packets_per_sec,down_up_ratio,...,backward_bulk_bytes,forward_bulk_packets,backward_bulk_packets,forward_bulk_rate,backward_bulk_rate,active,idle,forward_initial_window_size,backward_initial_window_size,forward_last_window_size
0,ClDOIi3yLGMfeRPzAc,103.255.15.23,49188,13.227.228.83,443,1.738424,8.628505,NaN,16.681776,NaN,...,0.0,0.0,NaN,NaN,0.000000e+00,1.738440e+06,NaN,29200.0,65535.0,80.0
1,C9chsd1cHTOBBHe6Q2,202.169.224.219,5678,255.255.255.255,5678,0.000000,0.000000,0.000000,0.000000,0.0,...,NaN,0.0,NaN,NaN,NaN,0.000000e+00,0.0,0.0,0.0,0.0
2,CUOe3U1NC5Nln7cItf,103.255.15.150,32976,8.8.8.8,53,NaN,80.446972,NaN,NaN,1.0,...,0.0,NaN,0.0,0.0,0.000000e+00,2.486110e+04,0.0,0.0,0.0,NaN
3,C6QhB04KTRUYOY2rMk,103.255.15.150,48606,128.199.242.104,443,NaN,NaN,51.891033,88.956056,NaN,...,4585.0,0.0,5.0,0.0,1.544649e+07,2.697961e+05,0.0,29200.0,NaN,NaN
4,C60oC51SZNEhCXlX6c,103.255.15.150,34794,128.199.242.104,443,0.326490,30.628816,NaN,70.446278,1.3,...,4585.0,0.0,NaN,NaN,5.211622e+07,NaN,NaN,29200.0,NaN,402.0

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
def plot_category_counts(data, column_name):
    
    counts = data[column_name].value_counts()
    
    sorted_counts = counts.sort_values(ascending=False)
    sorted_proportions = sorted_counts / sorted_counts.sum()
    
    plt.figure(figsize=(12, 8))
    ax = sns.barplot(x=sorted_counts.index, y=sorted_counts.values, palette='viridis')
    
    for bar in ax.patches:
        height = bar.get_height()
        category_name = bar.get_x() + bar.get_width() / 2
        proportion = sorted_proportions[sorted_counts.index[int(category_name)]]
        ax.text(bar.get_x() + bar.get_width() / 2, height + 0.02 * height, 
                f'{proportion:.2%}', 
                ha='center', va='bottom', fontsize=10)
    
    plt.xlabel('Category', fontsize=12)
    plt.ylabel('Count', fontsize=12)
    plt.title(f'Count of Each Category in {column_name}', fontsize=15)
    plt.xticks(rotation=45)  
    plt.show()

plot_category_counts(data, 'traffic')